### PR TITLE
Updated JQuery

### PR DESCRIPTION
**Pull request by NeamulIslamFahim**
## Adding a language

- [ ] The code displays "Hello World" ([tio.run](https://tio.run) may help for testing)
- [ ] I have updated the readme to include the new language
- [ ] I have incremented the language count in the readme
- [ ] I have no association with the language
- [ ] There are no copyright issues with this code
- [ ] The language has not been added prior to this pull request

### CODE REVIEW

**Comment by MrBrain295** [comment]
Can you add these changes to your other pull request?

**Comment by NeamulIslamFahim** [comment]
I have changed already. You can check

**Comment by NeamulIslamFahim** [comment]
JQuery is a library

**Comment by NeamulIslamFahim** [comment]
I have changed. You can check

**Pull request closed without merging**
