### PR TITLE
Create stale.yml

### PR DESCRIPTION
**Pull request by Tyler887**
I found a lot of stale issues in this project. What if they could be closed?

### CODE REVIEW

**Comment by MrBrain295** [comment]
@Tyler887 how did `stale.yml` get added?

**Comment by MrBrain295** [comment]
@Tyler887 do you have push access.

**Comment by Tyler887** [comment]
> @Tyler887 how did `stale.yml` get added?

It's an automated issue/PR closing action with `actions/stale`, a Node.js action to close inactive issues and pull requests.

**Comment by MrBrain295** [comment]
> > @Tyler887 how did `stale.yml` get added?
> 
> It's an automated issue/PR closing action with `actions/stale`, a Node.js action to close inactive issues and pull requests.

I know but no pr adding it was merged.

**Pull request closed without merging**
