### PR TITLE
Add Koa

### PR DESCRIPTION
**Pull request by ThePeeps191**
## Adding a language

- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme
- [x] I have no association with the language

### CODE REVIEW

**Comment by calgary34** [comment]
It's Koa.js not Koajs

**Comment by ThePeeps191** [comment]
I've fixed some conflicts

**Review by Richienb — CHANGES_REQUESTED** [review]
Follow the style of this file: https://github.com/leachim6/hello-world/blob/master/j/JavaScript.js

**Review by Richienb — CHANGES_REQUESTED** [review]
Increment the language count

**Comment by ThePeeps191** [comment]
I've made a new pull request

**Pull request closed without merging**
