### PR TITLE
Add JQuery

### PR DESCRIPTION
**Pull request by NeamulIslamFahim**
## Adding a language

- [ ] The code displays "Hello World" ([tio.run](https://tio.run) may help for testing)
- [ ] I have updated the readme to include the new language
- [ ] I have incremented the language count in the readme
- [ ] I have no association with the language
- [ ] There are no copyright issues with this code
- [ ] The language has not been added prior to this pull request

### CODE REVIEW

**Comment by MrBrain295** [comment]
You will need to update the readme.

**Comment by Richienb** [comment]
Are there any other Web 2.0 JavaScript libraries that have been added?

**Comment by MrBrain295** [comment]
There have been frameworks (eg., React, Vue, Svelte) but I don’t see any libraries.

**Comment by NeamulIslamFahim** [comment]
I have also seen frameworks. You can still have a check

**Comment by NeamulIslamFahim** [comment]
JQuery is a JS Library

**Comment by Richienb** [comment]
Given that libraries like MooTools don't already exists, there wouldn't be a reason for adding JQuery.

**Pull request closed without merging**
