### PR TITLE
Add CobolScript

### PR DESCRIPTION
**Pull request by MrBrain295**
I got my code from here [here](https://sites.google.com/view/cobolscripting/home/hello-world-example) (the commit message was wrong). Fixes part of: #790.

### CODE REVIEW

**Comment by Richienb** [comment]
The S in CobolScript seems to be capital.

**Comment by MrBrain295** [comment]
Done

**Comment by Richienb** [comment]
Is it CobalScript or CobolScript?

**Comment by MrBrain295** [comment]
CobolScript I keep making the same dumb typo

**Pull request merged**
