### PR TITLE
Add mariolang

### PR DESCRIPTION
**Pull request by mattmatt0**
From https://github.com/antoinelanco/MarioLANG

### CODE REVIEW

**Review by Richienb — CHANGES_REQUESTED** [review]
Remember to update the readme

**Comment by mattmatt0** [comment]
done

**Review by Richienb — CHANGES_REQUESTED** [review]
Remember to update the language count in the readme

**Review by Richienb — CHANGES_REQUESTED** [review]
Remember to update the language count in the readme

**Pull request closed without merging**
