### PR TITLE
Add ChaScript

### PR DESCRIPTION
**Pull request by NeamulIslamFahim**
## Adding a language

- [ ] The code displays "Hello World" ([tio.run](https://tio.run) may help for testing)
- [ ] I have updated the readme to include the new language
- [ ] I have incremented the language count in the readme
- [ ] I have no association with the language
- [ ] There are no copyright issues with this code
- [ ] The language has not been added prior to this pull request

### CODE REVIEW

**Comment by MrBrain295** [comment]
Can you please provide a link to the programming language.

**Comment by NeamulIslamFahim** [comment]
The link of the language
https://sjishan.github.io/chascript/

Thank you

**Comment by MrBrain295** [comment]
You still need to update the readme.

**Comment by NeamulIslamFahim** [comment]
Update done of the readme.

**Comment by NeamulIslamFahim** [comment]
Every thing is Alright?

**Comment by NeamulIslamFahim** [comment]
Will I be enlisted in the contribution list?

**Comment by Richienb** [comment]
The contributors list is automatically updated with every user that has contributed.

**Comment by MrBrain295** [comment]
@NeamulIslamFahim you might not be in the top 100 contributors so you might not be visible on the contributors list.

**Comment by NeamulIslamFahim** [comment]
Ok.
Got it.
Thanks for clarifying

**Pull request merged**
