### PR TITLE
Add Powerbuilder

### PR DESCRIPTION
**Pull request by ThePeeps191**
## Adding a language

- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme
- [x] I have no association with the language

#### Link to programming language: https://en.wikipedia.org/wiki/PowerBuilder

**fix #1217**

### CODE REVIEW

**Comment by Tyler887** [comment]
Duplicate of GH-1217

**Comment by ThePeeps191** [comment]
fixed some conflicts

**Comment by MrBrain295** [comment]
Does it print "Hello World" twice?

**Comment by ThePeeps191** [comment]
oh yes, lemme fix

**Comment by ThePeeps191** [comment]
fixed!

**Pull request merged**
