### PR TITLE
IRC

### PR DESCRIPTION
**Pull request by CubeFromSpace**
Found this randomly

### CODE REVIEW

**Comment by CubeFromSpace** [comment]
I feel more useful than earlier

**Comment by CubeFromSpace** [comment]
Also, if I delete my fork repo, will it affect this one?

**Comment by CubeFromSpace** [comment]
Oops, please rename it to IRP, not IRC

**Comment by CubeFromSpace** [comment]
I like comments

**Comment by CubeFromSpace** [comment]
Nvm I'll do it

**Comment by CubeFromSpace** [comment]
Nvm this failed

**Comment by CubeFromSpace** [comment]
:p I feel less useful

**Comment by leachim6** [comment]
Hah, thanks for your contribution nonetheless @CubeFromSpace. Please feel free to submit pulls any time :)

**Pull request closed without merging**
