### PR TITLE
Add JScript

### PR DESCRIPTION
**Pull request by FinlayMcKie**
## Adding a language

- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme

### CODE REVIEW

**Comment by MrBrain295** [comment]
Could you provide a link to the languages website?

**Comment by FinlayMcKie** [comment]
> Could you provide a link to the languages website?



> Could you provide a link to the languages website?

**Comment by FinlayMcKie** [comment]
> Could you provide a link to the languages website?

[](https://en.wikipedia.org/wiki/JScript) there's not really a website or even documentation anymore :/

**Comment by FinlayMcKie** [comment]
did I just close my own PR ?? 🤦‍♂️

**Comment by Richienb** [comment]
You did.

**Comment by FinlayMcKie** [comment]
thats a first

**Comment by FinlayMcKie** [comment]
theres the [wikipedia article](https://en.wikipedia.org/wiki/JScript) i guess

**Comment by FinlayMcKie** [comment]
I'm not really sure anymore tbh, JScript is weird, you should probably just ignore this

**Comment by Richienb** [comment]
@MrBrain295 Next time, use squash merge.

**Pull request merged**
