### PR TITLE
Add Tunex Language

### PR DESCRIPTION
**Pull request by JavaSkan**
## Adding a language

- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme

### CODE REVIEW

**Review by MrBrain295 — APPROVED** [review]

**Comment by JavaSkan** [comment]
@MrBrain295 It is paused right now, but i will continue developing it as soon as i get better in programming, thank you for asking😅

**Comment by Richienb** [comment]
Could you link to the source code?

**Comment by JavaSkan** [comment]
> Could you link to the source code?

Well, i've done only the lexer and a small part of the error system, so it's not that intresting, it is a private repository. I should mention that i am not an expert of programming, the source code was written in Java first, then migrated to Python (yeah i now, just don't try to understand my goals 😆) , and now i'm thinking to convert it to the C language (because it's faster, if you optimize it 👀). To say that i am not an advanced developer that's why i paused it. I've done it for the fun but i didn't realize the size of the project and the time it takes me to continue its development

**Comment by JavaSkan** [comment]
Should i cancel the pull request ?

**Comment by MrBrain295** [comment]
no

**Comment by JavaSkan** [comment]
ok if u say so

**Comment by MrBrain295** [comment]
@JavaSkan we just need a link to the language website or repo.

**Comment by MrBrain295** [comment]
Due to our new Conflict of Interest policy this must be closed.

**Comment by JavaSkan** [comment]
> Due to our new Conflict of Interest policy this must be closed.

I think it's better because it's not an official language + I don't think it will see its "birth" so great choice, maybe in the future 👀 and for the source code sorry, I didn't check the messages and I don't want people making changes to my code when I will make public because it's a personnal exercice (and I've never done it before), if u want, I can link the python version of the interpreter (because there is a c version and it's the official one, and the python version which is the old one)

**Comment by MrBrain295** [comment]
@JavaSkan if you make your interpreter/compiler open source you have to approve before someone changes the code.

**Pull request closed without merging**
