### PR TITLE
Add Ni

### PR DESCRIPTION
**Pull request by calgary34**
## Adding a language

- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme

#### Link to programming language: 
https://www.deybismelendez.com/ni/

### CODE REVIEW

**Comment by MrBrain295** [comment]
Can you replace `DOG`

**Comment by calgary34** [comment]
> Can you replace `DOG`

Done

**Comment by MrBrain295** [comment]
Can you add `Ni` to the readme.

**Comment by calgary34** [comment]
> Can you add `Ni` to the readme.

It's already there

**Comment by MrBrain295** [comment]
Oh, 🤦

**Pull request merged**
