### PR TITLE
Added Shanghai

### PR DESCRIPTION
**Pull request by code2828**
Added Dongbei and Shanghai
Dongbei: https://github.com/zhanyong-wan/dongbei
Shanghai: https://github.com/cabuliwallah/shanghai-from-dongbei

Fix for #733 .

### CODE REVIEW

**Comment by code2828** [comment]
OK. I'm doing it now.

**Comment by gzhangdev** [comment]
上海话？ 你是sb吗？ @code2828  it is not computer language. Why add Shanghai?

**Comment by code2828** [comment]
gzhang-dev你TM才是sb呢你倒是看看这儿啊 [shanghai](https://github.com/cabuliwallah/shanghai-from-dongbei)
给爷整笑了

Ziim你咋不说不是呢
各种奇葩语言你咋不说不是呢
真有意思

**Comment by code2828** [comment]
@Richienb I don't know how but please mute this conversation.  This PR is already merged.

**Pull request merged**
