### PR TITLE
Add o:XML

### PR DESCRIPTION
**Pull request by MrBrain295**
## Adding a language
Add o:XML
- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme
fixes part of #790

### CODE REVIEW

**Comment by MrBrain295** [comment]
@Richienb does it matter if I use a commit message when making a pull request?

**Review by MrBrain295 — COMMENTED** [review]
Should it be o:XML or O:XML

**Comment by Richienb** [comment]
> Should it be o:XML or O:XML

It should be **o:XML** like on the [homepage](http://www.o-xml.org/).

**Comment by MrBrain295** [comment]
Done ✔️

**Comment by frasca617** [comment]
Thank you

On April 27, 2021, at 9:03 PM, Richie Bendall ***@***.***> wrote:

Merged #991 into master.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/leachim6/hello-world/pull/991#event-4653867429">https://github.com/leachim6/hello-world/pull/991#event-4653867429</a>", "url": "<a href="https://github.com/leachim6/hello-world/pull/991#event-4653867429">https://github.com/leachim6/hello-world/pull/991#event-4653867429</a>", "name": "View Pull Request" }, "description": "View this Pull Request on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by frasca617** [comment]
Hey, I shared some photos and videos with you. Click here to view and add your own: https://www.amazon.com/photos/groups/share/mrwz0VMOSmqA9arXxitLPA.hWFExGjVjwt6r1dGkhZ6-o?i=t

Get Outlook for Android<https://aka.ms/AAb9ysg>

**Pull request merged**
