### PR TITLE
Add Org-mode

### PR DESCRIPTION
**Pull request by Tyler887**
https://orgmode.org
## Adding a language

- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme

### CODE REVIEW

**Review by Richienb — CHANGES_REQUESTED** [review]
The text shouldn't be styled, like the Markdown example

**Comment by Tyler887** [comment]
> The text shouldn't be styled, like the Markdown example

Addressed.

**Review by Richienb — APPROVED** [review]

**Comment by Tyler887** [comment]
My pull has a conflict! I need to resolve it, then you can merge.

**Comment by Tyler887** [comment]
Solved conflict.

**Pull request merged**
