### PR TITLE
Add Zsq

### PR DESCRIPTION
**Pull request by nekoism**
## Adding a language

- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme

#### Link to programming language: 
https://github.com/JBYT27/zsq

### CODE REVIEW

**Comment by Tyler887** [comment]
I think the pull request's name should be **Add Zsq**, not the commit name.

**Comment by Tyler887** [comment]
Also, please provide a link to the language website and check all three boxes.

**Review by Tyler887 — CHANGES_REQUESTED** [review]
We usally don't have the exclamation mark at the end of the sentence. Change `print("Hello World!")` to `print("Hello World")`.

**Comment by nekoism** [comment]
I changed them

**Review by Tyler887 — CHANGES_REQUESTED** [review]
Please update `readme.md` to link to this file using Markdown (`[Zsq](z/Zsq.zsq)`) and increase the number of languages in the `readme.md`. If you have a local Git clone, run `update_list.py`.

**Comment by nekoism** [comment]
Done

**Comment by nekoism** [comment]
Is there anything else you want me to do?

**Comment by nekoism** [comment]
Update the readme.md

**Pull request merged**
