### PR TITLE
Update CSharp.cs

### PR DESCRIPTION
**Pull request by IgorSivirinov**
Due to the advent of .NET 6, the code for writing has changed (Hallo, World)
https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create

### CODE REVIEW

**Comment by Richienb** [comment]
It doesn't work because the System namespace is not imported.

**Comment by IgorSivirinov** [comment]
@Richienb starting with .NET 6 and C # 10, this is optional.  You
 exactly were they used?

**Comment by Richienb** [comment]
Could you show me the part of the changelog that mentions this?

**Comment by IgorSivirinov** [comment]
I can’t find this change, but I can give you documentation from Microsoft.
https://docs.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates

**Comment by IgorSivirinov** [comment]
@Richienb 
I can’t find this change, but I can give you official documentation from Microsoft.
https://docs.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates

**Pull request closed without merging**
