### PR TITLE
Use puts() for C

### PR DESCRIPTION
**Pull request by deltabeard**
Reverted back to the use of puts() since it is better for this case as
explained in commit 1b66868d5fd64bb6a677328764401fad96804ef3.

The reason given for the change from puts() to printf() in commit
52a8c332d87617f9e0ec59c6b81aad93afb1c220 was poor, and should not have
been accepted.

Functions that do not take a parameter in C must be declared with `void`
as its only parameter, otherwise you are describing a function with an
unspecified number of parameters.

The opening curly bracket is usually on a new line when declaring a function
in most code styles.

Signed-off-by: Mahyar Koshkouei <mahyar.koshkouei@gmail.com>

### CODE REVIEW

**Comment by Suzamax** [comment]
What about this Hello world?

```c
#include <stdio.h>

int main() {
    return printf("Hello World!\n");
}
```
As `printf` returns zero if it performs well, then there's no point in putting return 0, simply return the `printf` result :smile:

**Comment by deltabeard** [comment]
> As printf returns zero if it performs well

Actually `printf` [returns the number of characters printed](https://linux.die.net/man/3/printf). Exiting the program with an exit status set by the returned value of the printf may correspond to an error status despite an error not occuring.

In `stdlib.h`, the `EXIT_SUCCESS` macro is typically defined as `0`. Therefore, either `return EXIT_SUCCESS` or simply `return 0` should be used when no error has occured.

If printf fails, and returns a negative value, you could `return EXIT_FAILURE`.

There is still no reason to be using `printf` instead of `puts` here. You could have some error checking in there like below, but whats the point?

```
if(puts("Hello World") == EOF)
        return EXIT_FAILURE;

return EXIT_SUCCESS;
```

**Comment by Suzamax** [comment]
> > As printf returns zero if it performs well
> 
> Actually `printf` [returns the number of characters printed](https://linux.die.net/man/3/printf). Exiting the program with an exit status set by the returned value of the printf may correspond to an error status despite an error not occuring.

You're right, sorry :astonished: 

```
#include <stdio.h>

int main(void) { 
	return printf("Hello World\n") > 0 ? 0 : 0;
}
```
Better approach. Still using `printf` as `stdio` is used  by almost everyone and `printf` is the first function everybody learns.

**Comment by deltabeard** [comment]
Your ternary if statement is incorrect, since you're returning `0` in both cases. You may as well just have `return 0` on the next line. I think you meant `return printf("Hello World\n") > 0 ? 0 : 1`.

I do agree that printf is more common amongst beginners. It depends if we want to write code that is more "correct" as opposed to code that is more common. If we want to make this hello world as simple as possible, maybe we should have:

```c
#include <stdio.h>

int main(void)
{ 
	printf("Hello World\n");
	return 0;
}
```

Apart from the opening brace and the function argument for main being set to `void`, the above code is what we already have. If we want the code to be simple, then I can close this pull request. Thoughts?

**Comment by deltabeard** [comment]
Why was this closed? The issue has not been fixed.

**Comment by Richienb** [comment]
@deltabeard Whoops, reopened.

**Comment by Richienb** [comment]
The solution suggested in https://github.com/leachim6/hello-world/pull/587#issuecomment-474972927 seem to be the best way to go. Closing.

**Comment by MrBrain295** [comment]
@Richienb the “help needed” label needs removed.

**Pull request closed without merging**
