### PR TITLE
Update c.c

### PR DESCRIPTION
**Pull request by gauravjain2**
Reduced the number of Lines of Code.

### CODE REVIEW

**Comment by rdebath** [comment]
The `int` return type is supposed to be there in all versions and the `return 0` is required in pre-c99 versions. You might create a `c/c99.c` version as C99 without the `return 0` as it will be the default the end of main.

**Comment by Ronkiro** [comment]
Wasn't it recommended as a good practice, btw? I don't think it's creation would be good for this purpose, but it could still be created just to separate C versions.

**Comment by rdebath** [comment]
The standard itself doesn't say anything; there is a rationale statement that says the default `return 0` was to accommodate the existing bad programmers in the same way that some C compilers do.  So, I guess. Personally, I always though it'd usually be using the return value of the last function call 'cause that's what was left in the `A` register.

**Comment by gauravjain2** [comment]
The code without return 0 statement works well.

**Comment by Ronkiro** [comment]
> The code without return 0 statement works well.

This depends on which C version you are compilling. This isn't an universal (for all C versions)

**Comment by Richienb** [comment]
Let's not add extra confusion and stick with the most supported standard.

**Pull request closed without merging**
