### PR TITLE
Change GitHub Actions triggers

### PR DESCRIPTION
**Pull request by Tyler887**
Only the `workflow_dispatch` trigger is not enough, so I'm adding a `push` trigger to the workflow.

### CODE REVIEW

**Comment by MrBrain295** [comment]
Can you remove the comment.

**Comment by Tyler887** [comment]
> Can you remove the comment.

Thanks! See aed8bda.

**Comment by MrBrain295** [comment]
I don’t have much gh actions experience so I requested @Richienb to review.

**Comment by Tyler887** [comment]
> I don’t have much gh actions experience

If that's the case, you can use [GitHub Learning Lab](https://lab.github.com). It has a course related to GitHub Actions.

You can also use [some starter workflows][starter].

[starter]: https://github.com/actions/starter-workflows

**Comment by Richienb** [comment]
> Only the `workflow_dispatch` trigger is not enough

I think it **is** enough. The Hello World script is used for demonstration purposes and in that context, shouldn't be run for every push but instead when the demonstration is requested via a manual activation.

**Pull request merged**
