### PR TITLE
Add es

### PR DESCRIPTION
**Pull request by MrBrain295**
## Adding a language
part of #790
- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme

### CODE REVIEW

**Comment by MrBrain295** [comment]
@Richienb does it help if when adding a language if I do a commit message or not?

**Comment by MrBrain295** [comment]
thanks

**Comment by MrBrain295** [comment]
@Richienb does anything need fixing?

**Comment by Richienb** [comment]
Could you link to this programming language?

**Comment by MrBrain295** [comment]
https://en.m.wikipedia.org/wiki/Rc#es

**Pull request closed without merging**
