### PR TITLE
Add Like, Python

### PR DESCRIPTION
**Pull request by MrBrain295**
## Adding a language

- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme
https://jon.how/likepython/

### CODE REVIEW

**Comment by MrBrain295** [comment]
It could be just “print(“Hello World”)” but this shows off the lang more.

**Comment by MrBrain295** [comment]
@Richienb should I keep it like python or show off the lang?

**Comment by Richienb** [comment]
> @Richienb should I keep it like python or show off the lang?

The current version is good enough.

**Comment by MrBrain295** [comment]
@Richienb I try to make my code as good as possible rather then "good enough" is there any way I could improve it?

**Comment by Richienb** [comment]
> @Richienb I try to make my code as good as possible rather then "good enough" is there any way I could improve it?

When you open a PR, I will always check the code and give you review suggestions to make it better.

**Pull request merged**
