### PR TITLE
Add Miranda

### PR DESCRIPTION
**Pull request by abt8601**
## Adding a language

- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme

Part of #790.

## How to run

Requirement: Miranda interpreter v2.066 (can be built in Debian Stretch)

```
$ mira -exec m/Miranda.m
```

### CODE REVIEW

**Review by warrenferns — COMMENTED** [review]
Looks Good!

**Review by MrBrain295 — APPROVED** [review]
Looks good 👍

**Comment by MrBrain295** [comment]
@Richienb i think it’s ready unless you want it to run with the normal interpreter.

**Comment by MrBrain295** [comment]
I don’t think it will get merger unless it works with the normal interpreter

**Comment by abt8601** [comment]
Well, the problem is that, it is the interpreter *itself* that doesn't compile. I guess we'll have to wait for the next release and see if this problem will get fixed.

**Comment by MrBrain295** [comment]
Oh it doesn’t have to compile just run so if it runs with the interpreter that’s fine.

**Comment by abt8601** [comment]
The interpreter (version 2.066) doesn't have a binary release, so I'll have to compile from the source code to get the interpreter in the first place. Now that it doesn't compile, I'm left with no "normal" interpreter to work with.

Miranda v2.042 does have a binary release, but the current program doesn't run on that version of the interpreter. If I rewrite the program for v2.042, then the program won't run on v2.066.

**Comment by MrBrain295** [comment]
Oh, got it.

**Comment by MrBrain295** [comment]
I thought you made modifications to the interpreter to make it run.

**Comment by abt8601** [comment]
I successfully got the original interpreter running. The interpreter compiles and runs in Debian Stretch (GCC 6.3.0, can be installed via apt-get), the environment in which the interpreter is most likely to be developed. The description has been updated accordingly.

**Review by MrBrain295 — APPROVED** [review]

**Comment by Richienb** [comment]
> I successfully got the original interpreter running. The interpreter compiles and runs in Debian Stretch (GCC 6.3.0, can be installed via apt-get), the environment in which the interpreter is most likely to be developed. The description has been updated accordingly.

Were you able to successfully run the code?

**Comment by abt8601** [comment]
> Were you able to successfully run the code?

Yes. The code behaves as intended.

**Pull request merged**
