### PR TITLE
Update mysql.sql

### PR DESCRIPTION
**Pull request by Oxicode**

### CODE REVIEW

**Comment by Hyftar** [comment]
Can you provide some context on this PR?

**Comment by Oxicode** [comment]
The DUAL is special one row, one column table present by default in all Oracle databases. 
The table has a single VARCHAR2(1) column called DUMMY that has a value of 'X'. **MySQL allows DUAL to be specified as a table in queries that do not need data from any tables**. In SQL Server DUAL table does not exist, but you could create one.
 The DUAL table was created by Charles Weiss of Oracle corporation to provide a table for joining in internal views.

**Comment by Shmakov** [comment]
@Oxicode I don't think it is necessary to make changes into mysql, as there is a separate file for the "Oracle SQL language" ([oraclesql.sql](https://github.com/leachim6/hello-world/blob/master/o/oraclesql.sql)) and that one does use DUAL table. What do you think?

**Comment by Oxicode** [comment]
okey

**Pull request closed without merging**
