### PR TITLE
Add json.json

### PR DESCRIPTION
**Pull request by g-liu**
Because markup languages count too!

### CODE REVIEW

**Comment by greensn0w** [comment]
Hello world in every **programming** language.
You need another programming language to print the "Hello World", so **-1** from me.

**Comment by RhysBower** [comment]
I would have to agree with @greensn0w the json is not a programming language.  The reason that we should not accept this change is because if the project goes in a direction of providing a sample program for each language we will be unable to write one for json.

**Comment by g-liu** [comment]
Other non-programming languages in this repo:

https://github.com/leachim6/hello-world/blob/master/x/xml.xml
https://github.com/leachim6/hello-world/blob/master/h/html.html
https://github.com/leachim6/hello-world/blob/master/c/css.css
https://github.com/leachim6/hello-world/blob/master/x/xslt.xslt

Please let me know why these qualify and JSON does not.

**Comment by RhysBower** [comment]
I totally see where you are coming from. Perhaps we should accept this pull request right now because of the above mentioned languages. However take a look at issue #158 in which we are discussing if this project will morph into something more than printing "hello world".

**Comment by rdebath** [comment]
I think neither this nor the xml.xml should be (have been) accepted. The html, css and xslt are acceptable because
* xslt is actually Turing complete so is literally a programming language.
* The html and css when processed "in the normal way" both provide just "Hello World!" with no extra characters.

The XML could be rescued if it's reformulated as xhtml; possibly. 
 However, I don't see any 'normal processing' that would make the json work.

**Pull request merged**
