### PR TITLE
Add Tom's Obvious, Minimal Language and hungarian language examples

### PR DESCRIPTION
**Pull request by pharsfalvi**
## Adding a language

- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme

### CODE REVIEW

**Review by MrBrain295 — CHANGES_REQUESTED** [review]
The comment in TOML needs removed.

**Comment by pharsfalvi** [comment]
@MrBrain295 - thanks for your review, the comment is now removed.

**Review by MrBrain295 — APPROVED** [review]

**Comment by Richienb** [comment]
Since TOML was added in a seperate PR, the one added by this one is no longer needed.

**Comment by pharsfalvi** [comment]
ack, closing...

**Pull request closed without merging**
