### PR TITLE
Remove deprecated nodejs

### PR DESCRIPTION
**Pull request by thathexa**
There were 2 nodejs files (`node.js` and `nodejs.js`), one of which used process.stdout, which is highly disfavored over console.log. Kept only one file named `nodejs.js` (`nodejs` is a more informative and correct name than `node`), which uses `console.log`.

### CODE REVIEW

**Comment by rdebath** [comment]
I don't see anything that says `process.stdout` is deprecated.
I do see warnings, however; possibly important ones here say that `process.stdout` may block and `console.log` may not output it's string at all.

As the whole purpose of the program is to send stuff to stdout blocking is not important and loss of the output rather defeats it. So in this particular case `process.stdout` would be preferred!

**Comment by thatHexa** [comment]
Why would `console.log` lose the output?

**Comment by rdebath** [comment]
Dunno why; I'm just looking at the docs: https://nodejs.org/docs/latest/api/process.html#process_a_note_on_process_i_o

And they seem to be saying that if decides to go async you might lose the output and that `console.log` is always async. 
BUG? In the system or the docs?

**Comment by nitrix** [comment]
If you do remove `node.js` you should update `README.md`. It lists both Node and Node.js.

**Comment by Qix-** [comment]
Best practices for a hello world program generally agree with @thathexa here - `console.log()` is proper.

**Pull request merged**
