### PR TITLE
Improve ATS example

### PR DESCRIPTION
**Pull request by SentinelWarren**

### CODE REVIEW

**Comment by Richienb** [comment]
@SentinelWarren Can't we just do this?

```ats
val () = println! "Hello World"
```

**Comment by SentinelWarren** [comment]
We can't, will actually need `foo main ()` for the code execution just like in `C`. Where as `implement` is the keyword for defining the function `main0`. ATS programs starts at `main0` function.

That said `implement main0 () = println! "Hello World"` could be near the `val () = println! "Hello World"` outcome in this case where as we will just pass the value of `println!` function direct to the function `main0` without pre defining the value using `val` keyword.

**Comment by SentinelWarren** [comment]
> @SentinelWarren Can't we just do this?
> 
> ```ats
> val () = println! "Hello World"
> ```

We can't, will actually need `main ()` function for the code execution just like in `C`. Where as `implement` is the keyword for defining the function `main0`. ATS programs starts at `main0` function.

That said `implement main0 () = println! "Hello World"` could be near the `val () = println! "Hello World"` outcome in this case where as we will just pass the value of `println!` function direct to the function `main0` without pre defining the value using `val` keyword.

**Comment by Richienb** [comment]
@SentinelWarren So you mean we can do this?

```ats
implement main0 () = println! "Hello World"
```

**Comment by SentinelWarren** [comment]
> @SentinelWarren So you mean we can do this?
> 
> ```ats
> implement main0 () = println! "Hello World"
> ```

@Richienb Yes ofcourse we can.

**Pull request merged**
