### PR TITLE
Add nearly to “all computer languages”

### PR DESCRIPTION
**Pull request by MrBrain295**
Makes it less confusing.

### CODE REVIEW

**Comment by MrBrain295** [comment]
@Richienb would this be needed or is it supposed to mean every computer language.

**Comment by Xrayez** [comment]
It should probably describe what the repository *aims* to do. It's more or less obvious that the repository cannot keep this up to date for every language that appears in the wild.

**Comment by Xrayez** [comment]
Perhaps just have to link #790 as a call for contributors to add more languages there.

**Comment by MrBrain295** [comment]
@Xrayez @Richienb should it be something like “Hello World in every computer language (if you want to add one see #790)”

**Pull request closed without merging**
