### PR TITLE
Fix readme listings for files with special characters

### PR DESCRIPTION
**Pull request by clemmyn23**
Use urllib.parse.quote() to percent-encode special characters (e.g. spaces) in file paths so the URLs render properly. 

Also added sorting since listdir() output order seems to vary across different file systems.  
(I couldn't replicate the original listing order on my Linux box without the sorts)

Screenshot before:
before2

Screenshot after:
after2

### CODE REVIEW

**Comment by leachim6** [comment]
Thanks for the contribution @clemmyn23 !

**Comment by controversial** [comment]
This undid #399. I'm going to re-submit #399 in a new PR.

**Comment by controversial** [comment]
See #402

**Comment by leachim6** [comment]
Sorry about that @controversial ! We should be all good now

**Pull request merged**
