### PR TITLE
changed to python 3

### PR DESCRIPTION
**Pull request by cpt-nem0**

### CODE REVIEW

**Review by frasca617 — APPROVED** [review]

**Comment by Richienb** [comment]
That's what `python3.py` is for.

**Comment by frasca617** [comment]
Am I doing this right? Lol

**Comment by Richienb** [comment]
The readme lists 2 files: `Python`, the Python 2 version and `Python 3`, the Python 3 version.

You are trying to edit the `Python` version and make it Python 3.

**Comment by Richienb** [comment]
Alternatively, we could rename `Python` to `Python 2` for extra clarity.

**Pull request closed without merging**
