### PR TITLE
Rename ~English.ext to ~English

### PR DESCRIPTION
**Pull request by calgary34**
It seems that all of the natural languages don't have a file extension, except for English, so I renamed it.

### CODE REVIEW

**Comment by MrBrain295** [comment]
I left this because there is an esolang called `English` that uses the file extension.

**Comment by calgary34** [comment]
@MrBrain295 Yes, but all of the natural languages start with a tilde.

**Comment by ThePeeps191** [comment]
@MrBrain295 @calgary34 means that `English` is different from `~English`

**Comment by Richienb** [comment]
> I left this because there is an esolang called `English` that uses the file extension.

Not sure if there would be a conflict:

- `~English`
- `English.ext`

**Pull request closed without merging**
