### PR TITLE
Add uwu language

### PR DESCRIPTION
**Pull request by swatiaggrawal**
added hello world in Uwu Language

### CODE REVIEW

**Comment by swatiaggrawal** [comment]
I have updated the readme to include the new language
 I have incremented the language count in the readme
 I have no association with the language
 There are no copyright issues with this code
 The language has not been added prior to this pull request

**Comment by MrBrain295** [comment]
I need a link to the programming language before I can merge.

**Comment by swatiaggrawal** [comment]
This was all from where i got to know about it:
https://esolangs.org/wiki/UwU
https://github.com/Deltaphish/UwUpp
https://github.com/KiraDotRose/UwU

**Comment by swatiaggrawal** [comment]
@MrBrain295 could you add the hactober fest accepted label please

**Comment by Richienb** [comment]
Merges already count as an acceptance:

> [Maintainers of opted-in projects can accept PR/MRs from contributors by merging them](https://www.digitalocean.com/blog/hacktoberfest-2022-your-mission-for-open-source#how-to-participate:~:text=Maintainers%20of%20opted%2Din%20projects%20can%20accept%20PR/MRs%20from%20contributors%20by%20merging%20them)

**Comment by swatiaggrawal** [comment]
okay thanks 🙂

**Pull request merged**
