### PR TITLE
Update bash.bash

### PR DESCRIPTION
**Pull request by bfaist**
Semicolon is not required.

### CODE REVIEW

**Comment by rdebath** [comment]
Hmmm, you know the quotes aren't needed either.

**Comment by lmorg** [comment]
Quotes / no quotes. Doesn't matter. Best practice would be to enclose the text in quotes for readability. However the exclamation mark will cause the Bash script to fail as the exclamation mark is a history variable.

I can't do a pull request as away without laptop, but I'd suggest generating the exclamation mark with 'printf' with the ASCII character code to generate that particular dumb symbol.

**Comment by lmorg** [comment]
I wasn't meant to say "dumb" in my comment. Damn auto correct

**Comment by mkody** [comment]
For the exclamation mark, we could use single-quotes instead.

```diff
@@ -1,3 +1,3 @@
 #!/bin/bash
 
- echo "Hello World!"; 
+ echo 'Hello World!'
```

**Comment by deanturpin** [comment]
Does anybody use the extension .bash?!

**Comment by lmorg** [comment]
Single quotes doesn't escape exclamation marks in bash. Hence the printf suggestion.

**Comment by lmorg** [comment]
The extension is moot. What matters is the execution bit and the shebang on the first line. Aside that, you can call the script whatever you like with whatever extension you like. It's purely personal preference

**Comment by rdebath** [comment]
Bash and even CSH (where the ugly `!2`,`!x` syntax came from) only evaluate the history `!` if it's syntactically valid, a `!` at the end of the line is NOT valid so it's just text not a history reference.

But the point is in fact moot too because (AFAIK) bash has NEVER evaluated history references in a shell script, just on the command line (unlike csh).

**Comment by lmorg** [comment]
Has anyone actually tested the code?  I'm still away so no access to computer

**Comment by deanturpin** [comment]
It does work with no quotes.

**Pull request merged**
