### PR TITLE
Add Panther

### PR DESCRIPTION
**Pull request by AliRn76**
## Adding a language

- [x] The code displays "Hello World"
- [ ] I have no association with the language
- [x] There are no copyright issues with this code
- [x] The language has not been added prior to this pull request

#### Link to programming language: 
https://pantherpy.github.io/

### CODE REVIEW

**Review by Richienb — APPROVED** [review]

**Comment by Richienb** [comment]
conflict of interest?

**Comment by AliRn76** [comment]
> conflict of interest?

Sry, what do you mean?

**Comment by AliRn76** [comment]
Is it ok? 
https://www.linkedin.com/posts/pythondeveloper_do-you-use-panther-python-framework-for-your-activity-7092931034966544384-C8kM/?utm_source=share&utm_medium=member_desktop

**Review by MrBrain295 — APPROVED** [review]
LGTM. Good proof of relevance.

**Pull request merged**
