### PR TITLE
Add FastAPI

### PR DESCRIPTION
**Pull request by SajadRahimi1**
## Adding a language

- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme

### CODE REVIEW

**Comment by Richienb** [comment]
The capitalisation should reflect the official version: **FastAPI**

**Comment by SajadRahimi1** [comment]
> The capitalisation should reflect the official version: **FastAPI**

 capitalisation Done

**Comment by Richienb** [comment]
@SajadRahimi1 Check again

**Comment by SajadRahimi1** [comment]
> @SajadRahimi1 Check again

Rename applied

**Comment by Richienb** [comment]
@SajadRahimi1 Check again

**Pull request merged**
