### PR TITLE
Fix Minecraft

### PR DESCRIPTION
**Pull request by DBTDerpbox**
Removed the `/` at the start of the first line due to the fact that MCF won't run any lines that start with `/`

### CODE REVIEW

**Review by MrBrain295 — APPROVED** [review]
This change would be needed for command block but  if your doing this through chat the slash would be needed.

**Review by MrBrain295 — COMMENTED** [review]
This change would be needed for command block but if your doing this through chat the slash would be needed.

**Comment by MrBrain295** [comment]
Sorry no approve just comment.

**Comment by Richienb** [comment]
Since this is an `mcfunction` file, it is supposed to contain commands that are executed without slashes

https://minecraft.fandom.com/wiki/Function_(Java_Edition)#Running_a_function

**Pull request merged**
