### PR TITLE
Add Persian

### PR DESCRIPTION
**Pull request by Merati22**
## Persian

- [ ] The code displays "Hello World"
- [ ] I have updated the readme to include the new language
- [ ] I have incremented the language count in the readme

### CODE REVIEW

**Comment by Merati22** [comment]
This is for Persian Language !

**Comment by Richienb** [comment]
If you are intended to provide a Persian translation of the [English text](https://github.com/leachim6/hello-world/blob/master/%23/~English.ext), you should do that instead.

If *Persian* really is a language, please provide a supplementary link.

**Comment by calgary34** [comment]
Persian was added in #1143

**Comment by MrBrain295** [comment]
> Persian was added in #1143

@calgary34 Thanks for noticing!

**Pull request closed without merging**
