### PR TITLE
Update c.c to ISO standart

### PR DESCRIPTION
**Pull request by paulkramme**

### CODE REVIEW

**Comment by rdebath** [comment]
There is nothing wrong with the existing code.
In an ANSI function _definition_ the `(void)` and `()` are identical.
In an ANSI function _declaration_ the `()` means unknown parameters and is "an obsolescent feature" in C11.

I would expect that in some future version the standards people will want to remove the weird `int main(void)` construct and have an empty parameter list mean "an empty parameter list" in all cases. 

Lastly, there's nothing in the existing code that says it's ANSI-C. It's current construction means the same thing in both ANSI and K&R C.

**Comment by paulkramme** [comment]
Well, to me it makes sense. It's like if someone calls you and asks you something, you declare what you want to have. And if you want nothing, you say nothing and aren't just answering.

**Comment by rdebath** [comment]
Yes, natural language (well English) generally uses a noun for "nothing", the _grammar_ doesn't include the concepts of an empty set. In maths and programming languages  OTOH it's more usual to use the context more explicitly so that `()` is an empty list/set. Even including languages that have the concept of `NULL` or `nil` the only language that I can think of that includes the explicit `nil` (`void`) in a parameter list is ANSI-C. They were basically forced to do something like this because they wanted to be able to compile mixed K&R and Ansi-C without errors.

**Comment by paulkramme** [comment]
Oh well, you've got a point. Is there any hope this mess will be fixed in
an upcoming new standart? Till then, why not make a file for both, lets say
cansi.c and ckr.c which contains a note about why this is.

**Comment by paulkramme** [comment]
BTW, i found another one: Python. There is the "None" value...

**Comment by rdebath** [comment]
Presumably this format is now "obsolescent" so they can replace (fix) it later.

> ... another one: Python. ...

Do you mean `None` is another `nil` or `NULL` 'cause there are no "declarations" in Python and ...
``` python

def print_none(None):
    print "I got nothin'."

print_none()
```
``` script
  File "/tmp/tst.py", line 2
    def print_none(None):
SyntaxError: cannot assign to None
```

As for more nulls, some languages have multiple `null` variants in one language; sometimes they look like they might be a good idea (javascript's `null` and `undefined`) other times they're just weird (Visual Basic 6).

**Pull request closed without merging**
