### PR TITLE
Added C90 and C++98

### PR DESCRIPTION
**Pull request by Vivekyadavgithub**
Added older version of c and c++ as they are little different from current

### CODE REVIEW

**Comment by Richienb** [comment]
@Vivekyadavgithub Remember to add them to the readme.

**Comment by SirLynix** [comment]
This makes no sense, getch is not standard and the Hello World is the same for all standard C++ versions

**Comment by Richienb** [comment]
@SirLynix What does `getch` actually do?

**Comment by SirLynix** [comment]
It reads the input buffer without waiting for the enter key to be pressed (as opposed to standard function std::getchar). It's used to block the program until the user presses a key.

This shouldn't be part of a Hello World.

**Comment by Richienb** [comment]
@SirLynix Thanks for elaborating. I'll revert it.

**Pull request merged**
