### PR TITLE
Simplify PHP

### PR DESCRIPTION
**Pull request by navarr**
Utilize the PHP echo tag.  This keeps it PHP specific while not dropping down to HTML (Just Hello world)

### CODE REVIEW

**Comment by DawidMazurek** [comment]
It is not standarised way of displaying output and for basic example where someone doesn't know php it dims how it actually works

**Comment by navarr** [comment]
<?= is absolutely a normal and standard way of Output in PHP

**Comment by Ardakilic** [comment]
No, please don't merge this.

This is against PSR-1 coding standards:

http://www.php-fig.org/psr/psr-1/#1-overview

**Comment by navarr** [comment]
This is absolutely a standard method for echoing output in PHP.

It's called out and recognized in [PSR-1](http://www.php-fig.org/psr/psr-1/#1-overview)

**Comment by navarr** [comment]
@Ardakilic PSR-1 explicitly allows the usage of <?=

**Comment by Ardakilic** [comment]
OK my mistake sorry, however, my disagreement with this still stands:

http://www.hacksparrow.com/why-not-to-use-php-short-opening-tags.html

**Comment by navarr** [comment]
This is not a PHP Short Open Tag, and disabling Short Open tags will not disable the short echo tag

**Comment by Ardakilic** [comment]
Yeah, but [for the versions bigger than 5.4.0](http://php.net/manual/en/ini.core.php#ini.short-open-tag). We can never know which PHP version the end-user has.

I don't like the tag, because for me, it feels "hacky", and makes the syntax look more a template engine such as twig.

I've seen web server provider disabling `<?=` tag earlier, but I've never seen a web server provider disabling the `<?php` tag.

**Comment by navarr** [comment]
<?= is widely embraced by the PHP community and available in all supported PHP versions always.

**Comment by Ardakilic** [comment]
Not every server has PHP versions >5.4.0.

https://w3techs.com/technologies/details/pl-php/5/all ([link based on this stackexchange answer](http://webmasters.stackexchange.com/a/34148))

~%30 of servers serving PHP has not been introduced with PHP 5.4.0 yet.

Also, being embraced doesn't mean the language should be introduced with that.

I won't discuss further, we both have points in my opinion. I'll let @leachim6 decide

**Comment by DawidMazurek** [comment]
I think `<?= ` looks like total magic for php newcomers. It is also avoided in large-scale corporate software.
I will claim again it is not standarized way of outputing data. Please consider following situation:

```example.php
<?php

$someLogic = new logic();
$result = $someLogic->doSomething();

// we want to display some result here

$foo = 'bar'; // we continue execution here
```

Doing as you write, to do this, you have to break php block so it would look like this:
```example.php
<?php

$someLogic = new logic();
$result = $someLogic->doSomething();
?>
<?=$result; 
$foo = 'bar';
```
`<?=` is only usable in php templating, while echo'ing is always compatible in all contexts and it doesn't have to be treated  differently

**Pull request closed without merging**
