### PR TITLE
Include void in 'int main()' and add space to #include statement

### PR DESCRIPTION
**Pull request by Qix-**
1. Added a space between `#include` and `<stdio.h>` because code cleanliness is probably a good thing to have in this codebase.
2. Added back `void` in `int main()` since otherwise it's [technically not correct](http://stackoverflow.com/a/693794/510036) since the compiler isn't explicitly being told the argument types.

I know the `void` had been removed before but it's not technically correct without it.

### CODE REVIEW

**Comment by rdebath** [comment]
Direct from the C11 last draft:
``` C
int g() { /* ... */ } // RIGHT: g has type compatible with F
```

This is a valid program (NOT an example of broken code) taken from the body of the C11 standard 
``` C
#include <stddef.h>
size_t fsize3(int n)
{
      char b[n+3];       // variable length array
      return sizeof b;   // execution time sizeof
}
int main()
{
      size_t size;
      size = fsize3(10); // fsize3 returns 13
      return 0;
}
```

These two reinforce each-other to the effect that an empty argument list is valid in the definition of a function (but may require a compatible prototype) and the compiler must make it so that the `main()` function has a prototype that matches one of the two valid forms (args and no-args).

Note also, unlike your stackoverflow link, this is pure `C` _not_ a `C+C++` hybrid so the suggestions for C++ compatibility don't apply. 
Then the existing version has the nice property that it is even compatible with the ancient K&R version of C.

And finally, from "6.7.6.3 Function declarators (including prototypes)"
```
14 An identifier list declares only the identifiers of the parameters of the function. An empty
   list in a function declarator that is part of a definition of that function specifies that the
   function has no parameters. The empty list in a function declarator that is not part of a
   definition of that function specifies that no information about the number or types of the
   parameters is supplied.145)

145) See ''future language directions'' (6.11.6).

6.11.6
The use of function declarators with empty parentheses (not prototype-format parameter
type declarators) is an obsolescent feature.

```

ie: The `()` in a prototype says nothing, but in the function itself it is a valid empty list, for now.

**Comment by Qix-** [comment]
It all depends on which version of the spec you're referring to. There's a large reason why C11's adoption rate is slower than, say, C++11 - simply because most C applications must be backwards compatible to support compilers that do not fully adhere to the C11 specification (namely MSVC, which until relatively recently didn't fully support even the C99 standard).

So it really comes down to what is _pragmatic_ and what is the most _up-to-date_ (even if being up-to-date isn't the most pragmatic).

For 100% compatibility with things like embedded systems (beyond ARM) ANSI C (C89) is still used, which requires `void` as the only identifier in the parameter list as per &set;3.5.4.3:

> The special case of `void` as the only item in the list specifies that the function has no parameters.

However, interestingly enough the _draft_ specification states:

> The empty list in a function declarator that **is not part of a function definition** specifies that no information about the number or types of the parameters is supplied.

Which is what you expect, but then follows up with

> An empty list in a function declarator that **is part of a function definition** specifies that the function has no parameters.

(emphasis mine)

Since `main` is a definition, according to the draft spec then an empty parameter list (`main()`) should be allowed so long as you're not forward-declaring it.

However, this isn't the case in the specification's main example:

```
The function called at program startup is named main . The implementation declares no prototype for this function. It can be defined with no parameters:

         int main(void) { /*...*/ }
```

So it's unclear if what the spec means by _"no parameters"_ is `(void)` or `()`.

However, that's all C89 stuff. It really comes down to if you want to consider anything other than C11 not-actually-C - which, subjectively and in my own opinion, is not exactly safe when it comes to C in particular.

**Comment by jleffler** [comment]
Qix asked me about this. 

### What the C standard says

To my way of thinking, the 'future language directions' (§6.11) of ISO/IEC 9899:2011 is pretty clear.

**§6.11.6 Function declarators**

The use of function declarators with empty parentheses (not prototype-format parameter
type declarators) is an obsolescent feature.
 
**§6.11.7 Function definitions**
The use of function definitions with separate parameter identifier and declaration lists
(not prototype-format parameter type and identifier declarators) is an obsolescent feature.

Note what it says in **§5.1.2.2.1 Program startup:**

… It shall be defined with a return type of `int` and with no
parameters: `int main(void) { /* ... */ }` or with two parameters …

This explicitly uses the `(void)` notation because the `()` notation is obsolescent.

Taken together, these mean that `int main() { … }` is using an obsolescent notation — the `main()` part is a function declarator (that is part of a function definition too) with empty parenthesis.  It is currently valid C; it is historically valid prior to the C89/C90 standard.  However, it is not the preferred direction, being officially marked 'obsolescent'.  Of course, like other obsolescent features, it will continue to be supported by C compiles for years (a decade or more) after the obsolescent feature is removed from the standard.

When you use the `int main()` notation, you are not providing a declaration of the function with a prototype for the `main()` function, whereas `int main(void)` does specify a prototype.  This only matters if you are calling `main()` from within your own code.  With the empty parentheses, there is no checking on other calls to `main()`; with `(void)`, other calls to `main()` can be validated against the prototype — any arguments in a call to `main()` will generate a diagnostic, and attempts to assign `int (*funcptr)(int argc, char **argv) = main;` would elicit a diagnostic (pointer type mismatch) too.

In the specific case of `main()`, this is seldom a problem; most programs do not recursively call main so there's no problem with the absence of a prototype for checking those calls.  In the general case (other functions than `main()`), the fact that the function is defined with `SomeType other_func() { … }` means that there isn't a prototype in scope after the function definition — there is a declaration, but it is a declaration without a prototype, so no argument checking is required by the standard for calls made after (or during) the function definition, unless there's a separate prototype in scope for the function (maybe from a header).

### Where does this leave you?

It depends on your priorities.  If you want your code examples to be portable to the maximum possible set of versions, you'll continue to use the non-prototype notations, including `int main() { … }`.  If you want your code to be future proof (and portable back to compilers that are less than a quarter-century old), then you'll use the `int main(void) { … }` and use prototypes everywhere.

For my own use, I require prototypes.  Using GCC, I almost always specify `gcc -Wall -Wextra -Werror -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition -Wold-style-declaration -std=c11 …`.  This rejects the `int main()` notation, so I never use the notation in code I write, or have sway over.  If it is code someone else controls, I'm willing to make my case but for `main()`, it isn't worth a huge fight.  For any other function, the formal "this function takes no arguments" statement from using the prototype notation with `(void)` is highly beneficial in any header, and I prefer to keep headers consistent with implementation files, so both declarations and definitions contain explicit `SomeType some_function(void)` notation for both the declaration and definition.

Personally, I would use the `(void)` because it is valid for all the versions of C that I am concerned about and avoids the pending threat of becoming invalid (non-standard) when the notation is removed from the standard.  I ceased to worry about pre-standard compilers a decade ago or longer — maybe since the turn of the millennium, by any convenient definition of which is the first date in this millennium.

**Comment by rdebath** [comment]
As I said, "VERY strong opinions".

**Pull request closed without merging**
