### PR TITLE
Add $_$

### PR DESCRIPTION
**Pull request by MrBrain295**
## Adding a language

- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme

### CODE REVIEW

**Comment by MrBrain295** [comment]
https://esolangs.org/wiki/Hello_world_program_in_esoteric_languages

**Comment by MrBrain295** [comment]
im not sure if it prints "Hello World" as its from esolangs

**Comment by MrBrain295** [comment]
@Richienb some of these i dint know if anyone fully understands the syntax should i make prs for them?

**Comment by Richienb** [comment]
We preferably want to run it to be sure. https://github.com/Sxakalo/SUS

**Comment by MrBrain295** [comment]
ok ill start doing that

**Comment by MrBrain295** [comment]
perl doesn't like arm64

**Comment by Richienb** [comment]
What OS are you using?

**Comment by MrBrain295** [comment]
Ubuntu

**Comment by MrBrain295** [comment]
on a raspberry pi

**Comment by MrBrain295** [comment]
it has this error `Can't locate FILE/Temp.pm in @INC (you may need to install the FILE::Temp module) (@INC contains: /etc/perl /usr/local/lib/aarch64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/aarch64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/aarch64-linux-gnu/perl-base /usr/lib/aarch64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at main.pl line 2.
BEGIN failed--compilation aborted at main.pl line 2.
`

**Comment by MrBrain295** [comment]
I don't know what to do now it doesn't say sus is working (it says `Command 'sus' not found, did you mean:
  command 'sys' from deb openafs-client (1.8.6-5ubuntu1)
  command 'sds' from deb simh (3.8.1-6.1)
  command 'su1' from deb hxtools (20201116-1)
  command 'sur' from deb subtle (0.11.3224-xi-2.2build3)
  command 'eus' from deb euslisp (9.27+dfsg-7)
  command 'sks' from deb sks (1.1.6+git20210302.c3ba6d5a-3)
  command 'sos' from deb sosreport (4.1-1ubuntu1)
  command 'bus' from deb atm-tools (1:2.5.1-4)
  command 'subs' from deb libsubtitles-perl (1.04-2)
  command 'su' from deb util-linux (2.36.1-7ubuntu2)
  command 'ss' from deb iproute2 (5.10.0-4ubuntu1)
  command 'sum' from deb coreutils (8.32-4ubuntu2)
  command 'sup' from deb sup (20100519-3)
  command 'srs' from deb srs (0.31-6)
Try: sudo apt install <deb name>
)`

**Comment by Richienb** [comment]
The repository advises you to run `perl main.pl <commandline args>`

**Comment by MrBrain295** [comment]
Oh, ok.

**Comment by MrBrain295** [comment]
I'm gonna make a follow up later.

**Pull request closed without merging**
