### PR TITLE
Add CASL2, LINE Entry, Tonyu

### PR DESCRIPTION
**Pull request by gnuhead-chieb**
## Adding a language

- [x] The code displays "Hello World" ([tio.run](https://tio.run) may help for testing)
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme
- [x] I have no association with the language
- [x] There are no copyright issues with this code
- [x] The language has not been added prior to this pull request

#### Link to programming language: 
https://qiita.com/shintarou-akao/items/e752635a12e23a6a8102
https://entry.line.me/
https://www.tonyu.jp/Tonyu2.php

### CODE REVIEW

**Comment by gnuhead-chieb** [comment]
@MrBrain295 @Richienb

**Comment by MrBrain295** [comment]
I don’t know how to read the languages those sites use so it’s hard for me to tell if it a legit programming language.

**Comment by gnuhead-chieb** [comment]
Screenshot_20221128_131555
Screenshot_20221128_132027
Screenshot_20221128_132317

**Comment by gnuhead-chieb** [comment]
@MrBrain295

**Pull request merged**
