### PR TITLE
Create کوردیی ناوەندی

### PR DESCRIPTION
**Pull request by jwtiyar**
Adding Central Kurdish (ckb)

### CODE REVIEW

**Review by Richienb — CHANGES_REQUESTED** [review]
Remember to update the readme.

**Comment by jwtiyar** [comment]
> 
> 
> Remember to update the readme.

‌Thank you, But PR should be added then i can update readme. 
because now i can't find the location to the file on official repo.

**Comment by Richienb** [comment]
Tried your own repo? https://github.com/jwtiyar/hello-world/tree/patch-2

**Comment by jwtiyar** [comment]
> 
> 
> Tried your own repo? https://github.com/jwtiyar/hello-world/tree/patch-2

Sorry iam stupid i made wrong commit to different location. I will PR new one.

**Pull request closed without merging**
