### PR TITLE
Add Buddy Script

### PR DESCRIPTION
**Pull request by MrBrain295**
## Adding a language
Add Buddy Script
- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme

### CODE REVIEW

**Review by Richienb — CHANGES_REQUESTED** [review]
Isn't `BuddyScript` without a space?

**Comment by MrBrain295** [comment]
Yeah

**Comment by MrBrain295** [comment]
I deleted my fork I’ll make a new pr

**Comment by MrBrain295** [comment]
see #984

**Pull request closed without merging**
