### PR TITLE
Fix BC and add BC GNU

### PR DESCRIPTION
**Pull request by Mango0x45**
POSIX bc does not support `print`, that is just an extension added in the GNU implementation of bc

### CODE REVIEW

**Comment by Richienb** [comment]
Can we also add the actual bc code:

```bc
"Hello World\n"
```

**Comment by Mango0x45** [comment]
POSIX bc does not display newlines with strings. The output of "Hello World\n" would simply be "Hello World". So this code would not print out a newline, but it is still a "Hello World"

**Comment by rdebath** [comment]
This script will print HW with a newline:
``` bc
"Hello World!
"
```

```
$ ls -l `which bc`
-rwxr-xr-x  1 root        19456 Oct 19  1995 /usr/bin/bc
$ file `which bc`
/usr/bin/bc:    VAX demand paged pure executable
$
```

**Comment by Richienb** [comment]
Fixed in (https://github.com/leachim6/hello-world/commit/035ab612a789191b7ba08280d565edc39ad81ae9)

**Pull request merged**
