### PR TITLE
Good habit

### PR DESCRIPTION
**Pull request by SlimaKCoder**

### CODE REVIEW

**Comment by gravityfox** [comment]
Not actually good habit.

There's a very specific reason why you should never close the php tag of a pure php page.

It has to do with security.

You should look at it more closely before you make that change...

**Comment by SlimaKCoder** [comment]
"If a file is pure PHP code, it is preferable to omit the PHP closing tag at the end of the file. This prevents accidental whitespace or new lines being added after the PHP closing tag, which may cause unwanted effects because PHP will start output buffering when there is no intention from the programmer to send any output at that point in the script." - Anyone confirmed it?

**Comment by gravityfox** [comment]
That is PHP behavior.

It's so that you can embed it in things like html.

Buffering issues can cause all sorts of bizarre errors.

**Comment by leachim6** [comment]
In light of the information provided I am leaving the original PHP example without the closing tag.

**Pull request closed without merging**
