### PR TITLE
Added Telugu

### PR DESCRIPTION
**Pull request by SSUMANTH4539**
Written in Telugu Language..

### CODE REVIEW

**Comment by Richienb** [comment]
Remember to translate the rest of https://github.com/leachim6/hello-world/blob/master/%23/~English.ext

**Comment by Richienb** [comment]
@SSUMANTH4539 The point is to actually translate the instructions themselves, not execute them.

**Comment by SSUMANTH4539** [comment]
okay got it.

**Comment by SSUMANTH4539** [comment]
it's done

**Comment by Richienb** [comment]
Now just add it to the readme and increment the languages counter in the header.

**Pull request merged**
