### PR TITLE
Add Czech

### PR DESCRIPTION
**Pull request by jachymozo**
## Adding a language

- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme

### CODE REVIEW

**Comment by MrBrain295** [comment]
@jachymozo You have to update the readme and language count

**Comment by jachymozo** [comment]
> @jachymozo You have to update the readme and language count

It should be updated now.

**Review by MrBrain295 — APPROVED** [review]
Looks good to me

**Comment by jachymozo** [comment]
Ok, thanks for review. You can merge it.

**Comment by MrBrain295** [comment]
I don't have tho power to merge it.

**Comment by jachymozo** [comment]
Oh, ok.

**Comment by MrBrain295** [comment]
@Richienb does anything need fixed?

**Comment by jachymozo** [comment]
I think that everything is alright, it just needs to merge.

**Comment by MrBrain295** [comment]
I was asking @Richienb (a maintainer) to review or merge.

**Comment by MrBrain295** [comment]
@Richienb its ready to merge (just needs conflicts resolved @jachymozo)

**Pull request merged**
