### PR TITLE
Updated the list_langs python script to generate the Numer Bullet list 

### PR DESCRIPTION
**Pull request by mahavirhirani**
Hello All,

I have updated the list_langs python script to generate the Numer Bullet list in README file. 

it's good to have a bullet list as a number because of any person directly check numbers of language are available 

Thanks
Mahavir Hirani

### CODE REVIEW

**Comment by mahavirhirani** [comment]
Hello @leachim6 

Can you please review the code and merge the code as soon as possible because of any person come at this repos so that he/ she can find count for language directly 

thank
Mahavir Hirani

**Comment by mahavirhirani** [comment]
@leachim6 .......

**Comment by mahavirhirani** [comment]
Hello All,

Please check the preview of readme files : [https://github.com/leachim6/hello-world/blob/4c719aa48e6c6ceedd3c851c66c43a49529ef1c7/README.md](click here)

**Comment by Richienb** [comment]
This a list, not an instruction manual.

**Comment by mahavirhirani** [comment]
> This a list, not an instruction manual.

Hello @Richienb  
You are right but sometimes (all the time) the user or developer has the curiosity to find the number of the programming language where the "Hello World" programs are already written.

Currently, we manually count in the ReadMe file one by one.

Thanks
@mahavirhirani

**Comment by Richienb** [comment]
@mahavirhirani Added counter in https://github.com/leachim6/hello-world/commit/d970061863ebc91c05c1e7efaa56c63c224f3555.

**Pull request closed without merging**
