### PR TITLE
Create ceylon.ceylon

### PR DESCRIPTION
**Pull request by lucaswerkmeister**
http://ceylon-lang.org

### CODE REVIEW

**Comment by leachim6** [comment]
Duplicate

**Comment by lucaswerkmeister** [comment]
Well, #327 is older than this PR, but sure…

**Comment by leachim6** [comment]
sorry @lucaswerkmeister it was just the order in which I merged everything, the files were identical and I'd already merged the other. Please don't hesitate to contribute in the future.

**Comment by lucaswerkmeister** [comment]
Well they’re not entirely identical, I’ve left a comment to that effect on the other PR… but it’s not too important.

**Pull request closed without merging**
