### PR TITLE
Add Luau

### PR DESCRIPTION
**Pull request by Didward**
Luau (lowercase u, /ˈlu.aʊ/) is a fast, small, safe, gradually typed embeddable scripting language derived from Lua.

## Adding a language

- [x] The code displays "Hello World" ([tio.run](https://tio.run) may help for testing)
- [ ] I have updated the readme to include the new language
- [ ] I have incremented the language count in the readme
- [x] I have no association with the language
- [x] There are no copyright issues with this code
- [x] The language has not been added prior to this pull request

### CODE REVIEW

**Comment by Didward** [comment]
Forgot to add file extension 😅

**Comment by MrBrain295** [comment]
You need to update the readme.

**Review by Richienb — APPROVED** [review]

**Review by Richienb — CHANGES_REQUESTED** [review]
Update the readme

**Review by gnuhead-chieb — APPROVED** [review]
There is no need to update Readme by contributor right now

**Comment by gnuhead-chieb** [comment]
ping:@MrBrain295

**Pull request merged**
