### PR TITLE
Couple of languages added 

### PR DESCRIPTION
**Pull request by thelastsoyce11**
## Adding a language

- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme
- [x] I have no association with the language
- [x] There are no copyright issues with this code

#### Link to programming language: 
[charcoal](https://github.com/somebody1234/Charcoal)
[porth](https://gitlab.com/tsoding/porth)
..

### CODE REVIEW

**Comment by Richienb** [comment]
I'll need a link to all of them

**Comment by Richienb** [comment]
The PR title should list the languages

**Review by MrBrain295 — CHANGES_REQUESTED** [review]
You are going to need to delete the ones that are already added.

**Review by CyberPotat42 — CHANGES_REQUESTED** [review]
You need to remove changes in languages that already exist:

- a/Assembler Atari 2600.asm
- n/NoFlo.fbp
- r/R.R

if you think that they need to be changed, you can mention them in a new issue

**Pull request closed without merging**
