### PR TITLE
Add Pygame

### PR DESCRIPTION
**Pull request by calgary34**
## Adding a language

- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme
- [x] I have no association with the language

### CODE REVIEW

**Comment by ThePeeps191** [comment]
This code only creates a window titled "Hello World"

**Comment by ThePeeps191** [comment]
I will create a pull request for code that shows text on the actual window itself

**Comment by calgary34** [comment]
@MrBrain295 Should there be text on the window, or is the window title enough?

**Comment by MrBrain295** [comment]
> @MrBrain295 Should there be text on the window, or is the window title enough?

Preferably text in the window.

**Comment by MrBrain295** [comment]
> @MrBrain295 Should there be text on the window, or is the window title enough?

Preferably text in the window.

**Comment by calgary34** [comment]
@MrBrain295 then what font should I use?

**Comment by MrBrain295** [comment]
> @MrBrain295 then what font should I use?

If there is a default one then that but otherwise lets go with "Arial".

**Comment by calgary34** [comment]
@MrBrain295 now it displays text
image

**Pull request merged**
